### PR TITLE
9.0 Port almost all modules to v9

### PR DESCRIPTION
**Pull request by alexis-via**
I ported to v9 all the modules that can be ported today i.e. all modules except 2 that depend on other modules that are not ported to v9 yet.

### CODE REVIEW

**Comment by alexis-via** [comment]
One thing left: restore the demo data, which could not be updated because the account.journals in Odoo 9 don't have an xmlid. Once this is done, tests should work again (tests use the demo data).

**Comment by MOSAMAD** [comment]
:+1:

**Comment by brother-bernard** [comment]
:+1:

**Comment by gurneyalex** [comment]
@alexis-via the tests are red because some xmlids are not there. Can you look into this?

**Comment by alexis-via** [comment]
@gurneyalex As I explained in my comment dated October 19 2015, Odoo 9 doesn't have XMLIDs for account journals (and it's not the only accounting element that had XMLIDs in v8 but doesn't have XMLIDs any more in v9). This means that I can't use XML demo data in v9 as I did in v8. I don't know what is the right solution for this in v9. I tried a few things, but didn't find the right way to do it, so I gave up on this for the moment.

**Comment by alexis-via** [comment]
@gurneyalex I found some solution for the pb of missing XMLIDs for journals and accounts, so tests are now working (at least for donation and donation_recurring)

**Comment by alexis-via** [comment]
Note that one of the unittest of donation_direct_debit needs an improvement in OCA/bank-payment ; i'll do a PR on it soon.

**Comment by gurneyalex** [comment]
Hello,

There is an issue with the donation demo data, which causes a red build on runbot (journal_id seems to be required on donation.donation, or there is maybe a dependency issue)

**Comment by alexis-via** [comment]
Yes, journal_id is required on donation.donation ; the demo data says:

```
<field name="journal_id" model="account.journal" search="[('type', '=', 'bank')]"/>
```

So it should take the first bank journal (the demo data provides a bank journal in Odoo v9 if a chart of account is installed, but without any XMLID). It works well on Travis, so I don't understand why it doesn't work on runbot.

**Comment by gurneyalex** [comment]
I can reproduce the issue locally by running:

```
python odoo.py -d donation --addons-path=$OCA/bank-payment,$OCA/donation,$PWD/addons,$PWD/openerp/addons -i donation
```

in a fresh Odoo 9.0 checkout, and an initially empty donation database. The addons path obviously needs local adjusting. 

If I first install `account`, stop the instance and install donation then it works (and this is what the travis scripts do: first install the dependencies without running the tests, then install the repository modules with tests enabled):

```
python odoo.py -d donation --addons-path=$OCA/bank-payment,$OCA/donation,$PWD/addons,$PWD/openerp/addons -i account --stop-after-init
python odoo.py -d donation --addons-path=$OCA/bank-payment,$OCA/donation,$PWD/addons,$PWD/openerp/addons -i donation
```

I'm tempted to say that it's a good idea to allow people who want to locally test your addon to be able to install it on a fresh database (or on a database with a default base install and no apps), so maybe you need to create a bank journal in your demo data if no other bank journal is found, just to be sure that the installation will go smoothly.

**Comment by alexis-via** [comment]
@gurneyalex Thank you very much Alexandre for this very detailed bug analysis. I'll add this to my short-term TODO list.

**Comment by alexis-via** [comment]
If I create a bank journal in the demo data of the donation module, it fails elsewhere:

```
2016-10-07 05:18:59,282 4627 INFO o9_don1 openerp.addons.account.models.chart_template: Could not install chart of account since some accounts already exists for the company ((1,))
2016-10-07 05:18:59,283 4627 INFO o9_don1 openerp.modules.loading: loading l10n_generic_coa/../account/demo/account_bank_statement.yml
2016-10-07 05:18:59,484 4627 INFO o9_don1 openerp.modules.loading: loading l10n_generic_coa/../account/demo/account_invoice_demo.yml
2016-10-07 05:18:59,824 4627 ERROR o9_don1 openerp.tools.yaml_import: ('Configuration error!\nCould not find any account to create the invoice, are you sure you have a chart of account installed?', None)
Traceback (most recent call last):
  File "/home/alexis/new_boite/dev/odoo9/openerp/tools/yaml_import.py", line 884, in process
    self._process_node(node)
  File "/home/alexis/new_boite/dev/odoo9/openerp/tools/yaml_import.py", line 895, in _process_node
    self.process_record(node)
  File "/home/alexis/new_boite/dev/odoo9/openerp/tools/yaml_import.py", line 337, in process_record
    module, record_dict, record_id, noupdate=self.isnoupdate(record), mode=self.mode, context=context)
  File "/home/alexis/new_boite/dev/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo9/openerp/addons/base/ir/ir_model.py", line 1144, in _update
    res_id = model_obj.create(cr, uid, values, context=context)
  File "/home/alexis/new_boite/dev/odoo9/openerp/api.py", line 250, in wrapper
    return old_api(self, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo9/openerp/api.py", line 354, in old_api
    result = method(recs, *args, **kwargs)
  File "/home/alexis/new_boite/dev/odoo9/addons/account/models/account_invoice.py", line 339, in create
    raise UserError(_('Configuration error!\nCould not find any account to create the invoice, are you sure you have a chart of account installed?'))
UserError: ('Configuration error!\nCould not find any account to create the invoice, are you sure you have a chart of account installed?', None)
```

I won't spend any more time to fix this. It is a complex issue that only cause a problem for runbot. When you look more carefully, in the module l10n_generic_coa, it loads as demo the file "../account/demo/account_invoice_demo.yml" ; which means that the demo data of invoices is not loaded in the account module. I think it's exactly the same kind of problem we have here. We would need to move the demo data to a dedicated module, which would mean moving the tests to a dedicated module also (because currently the tests use demo data).

So I see 2 options:
1) we merge this PR as it is with a red runbot
2) someone else fixes this problem

**Comment by alexis-via** [comment]
If nobody is against option 1, I'll merge this tomorrow.

**Pull request merged**
