### PR TITLE
[12.0][MIG] donation

### PR DESCRIPTION
**Pull request by jarroyomorales**
Superseed #68 

@tbaden @Nikul-Chaudhary @etobella

### CODE REVIEW

**Comment by tbaden** [comment]
@jarroyomorales there is a false positiv in donation_report.py
this PR: https://github.com/OCA/donation/pull/76/files fixed it. You have to rebase the module to include this fix.

**Comment by jarroyomorales** [comment]
@alexis-via Thank you for your comment! I think this is now ready to review.

**Comment by jarroyomorales** [comment]
@tbaden Can you check?

**Review by tbaden — APPROVED** [review]
code review: lgtm

**Review by etobella — APPROVED** [review]

**Comment by etobella** [comment]
@OCA/donation-maintainers I think this is ready

**Comment by etobella** [comment]
@OCA/donation-maintainers

**Comment by etobella** [comment]
@pedrobaeza @gurneyalex Runbot is failing on donation but no error is raised. Any idea why could it happen? As soon as it is generated, it is skipped, but no error log is created :thinking:

**Comment by pedrobaeza** [comment]
Any line in https://github.com/OCA/donation/blob/12.0/.travis.yml#L20 has `TESTS=1`

**Comment by etobella** [comment]
Thanks @pedrobaeza !!! It is generating here now :smile:

**Comment by etobella** [comment]
@OCA/donation-maintainers It is green as a :green_apple: 
I think now it can be merged. Thanks for the help :smile:

**Comment by etobella** [comment]
@pedrobaeza bot did not finish the migration :sob:

**Pull request merged**
