### PR TITLE
9.0 backport

### PR DESCRIPTION
**Pull request by funbaker**
Backporting stuff from 10.0 to 9.0 as described in #31.

Backported commits are gathered with `git cherry`, manually selected and fitted to work with 9.0.

Tests are working in the local environment.

### CODE REVIEW

**Comment by funbaker** [comment]
Looks like the build is breaking because the dependencies from `oca_dependencies.txt` are not pulled.
Since tests are working locally, this _should_ work after mergin.

**Comment by funbaker** [comment]
@alexis-via do you have time to review this one? :)

**Review by alexis-via — APPROVED** [review]
Could you also try to make Travis green ? You will have to set product_analytic_donation to uninstallable=False, because it depends on the module product_analytic which doesn't exist in v9. This is one of the cause of the failing tests.

**Comment by funbaker** [comment]
travis is green now @alexis-via

**Comment by benbrich** [comment]
Ahoi,

 

ich wollte bei donation_base noch anbringen, dass es vlt nicht schlecht wäre im donors view nur partner anzuzeigen, die is_donor = true haben. Aktuell ist das nämlich quasi einfach nur der ganz normale contacts view. Dann wäre bestimmt noch ein Button neben add im Sinne von add existing (partner) um doppelerfassungen vorzubeugen.

 

Wo würde ich das am besten auf git anbringen? :) Wahrscheinlich bei den issues nech. Die sind ja aber immer übergreifend oder? Eigentlich ist das ja aber auch kein issue oder?

 

Greetz

 

Von: Stefan Becker [mailto:notifications@github.com] 
Gesendet: Sonntag, 1. April 2018 21:14
An: OCA/donation <donation@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [OCA/donation] 9.0 backport (#32)

 

travis is green now @alexis-via <https://github.com/alexis-via>

**Comment by pedrobaeza** [comment]
English please.

**Comment by benbrich** [comment]
Hi Pedro, and everyone else,

 

Sorry, things went a little to fast this evening and my mail should have reached Stefan only to check with him first.

 

I will create the “issue” right away because we’re off topic here.

 

Greetings from Hamburg

 

Ben

**Pull request merged**
