### PR TITLE
[FIX] travis linting

### PR DESCRIPTION
**Pull request by tbaden**
related to issue #75

### CODE REVIEW

**Comment by tbaden** [comment]
travis check is green on my fork:
https://travis-ci.com/tbaden/donation/builds/129880765

**Comment by tbaden** [comment]
will add the linting fixes for the other modules as well here. wip

**Comment by tbaden** [comment]
fork push travis check is green:
https://travis-ci.com/tbaden/donation/builds/129885539

**Comment by tbaden** [comment]
all green again with pedros sql approach:
https://travis-ci.com/tbaden/donation/builds/129893947

**Comment by tbaden** [comment]
@pedrobaeza travis still doesn't like your approach:
donation/report/donation_report.py:115: [E8103(sql-injection), DonationReport.init] SQL injection risk.
Use parameters if you can. - More info https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#no-sql-injection

do we need a change for the travis check or is something wrong in my way?

**Comment by tbaden** [comment]
@pedrobaeza do you have a moment for the [question](https://github.com/OCA/donation/pull/76#issuecomment-537413664)

**Comment by pedrobaeza** [comment]
I will check and tell you back

**Comment by pedrobaeza** [comment]
@tbaden I'm afraid it's a problem of pylint-odoo itself.

@moylop260 why this is detected as SQL injection: https://github.com/OCA/donation/pull/76/files#diff-a3987ca352ccb730a8d205643ed4e804R115-R124 ? It shouldn't, as it's using psycopg2 valid way. Maybe you are only checking for the format markers?

**Comment by moylop260** [comment]
It is a false red because of corner case
We will need fixing it from pylint-odoo

**Comment by pedrobaeza** [comment]
@moylop260 how can we avoid that false positive?

**Comment by moylop260** [comment]
Meanwhile,
`# pylint: disable=sql-injection`
in the line with the “error”

**Comment by yucer** [comment]
> @tbaden I'm afraid it's a problem of pylint-odoo itself.
> 
> @moylop260 why this is detected as SQL injection: https://github.com/OCA/donation/pull/76/files#diff-a3987ca352ccb730a8d205643ed4e804R115-R124 ? It shouldn't, as it's using psycopg2 valid way. Maybe you are only checking for the format markers?

Actually the new way seems not to be the advised way to pass parameters. The concern of SQL injection is valid. Are you sure it is a problem of *pylint-odoo*?

References:

- https://github.com/OCA/odoo-community.org/blob/master/website/Contribution/CONTRIBUTING.rst#no-sql-injection

- https://stackoverflow.com/questions/28120124/psycopg2-variables-format-for-creating-queries

Might passing the parameters to execute instead of to format ? 

Or maybe using sql.SQL just for the main query and let the methods that return the sql part to return normal strings ?

**Comment by tbaden** [comment]
@yucer it's a snippet from pedro and approved by moylop, so it should be fine.

**Comment by yucer** [comment]
[Here](https://www.psycopg.org/docs/sql.html#module-usage) is a way to use that:

Using named parameters to the format clause:

```python
query = sql.SQL("select {field} from {table} where {pkey} = %s").format(
    field=sql.Identifier('my_name'),
    table=sql.Identifier('some_table'),
    pkey=sql.Identifier('id'))
```

Or joining the consecutive parameters with *join*:

```python
query = sql.SQL("select {fields} from {table}").format(
    fields=sql.SQL(',').join([
        sql.Identifier('field1'),
        sql.Identifier('field2'),
        sql.Identifier('field3'),
    ]),
    table=sql.Identifier('some_table'))

```

**Review by yucer — APPROVED** [review]

**Review by yweng8111 — APPROVED** [review]

**Pull request merged**
