### PR TITLE
Better demo data

### PR DESCRIPTION
**Pull request by alexis-via**
for my presentation at Odoo Experience 2015 !

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Why the empty file?

**Comment by alexis-via** [comment]
@pedrobaeza There is no empty file :) It's just an extra empty line that I removed.

**Comment by pedrobaeza** [comment]
Sorry, I was looking with the mobile view and I didn't see it.

:+1:

**Comment by brother-bernard** [comment]
:+1:

**Pull request merged**
