### PR TITLE
[14.0][IMP] add state of donation.tax.receipt

### PR DESCRIPTION
**Pull request by yweng8111**
We want to add the field state for "donation.tax.receipt".

### CODE REVIEW

**Comment by yweng8111** [comment]
hi @alexis-via ,
Can you please help me to fix the pre-commit error? I didn't get that error locally.

**Comment by melutovich** [comment]
@yweng8111 What is your pull request about?  Did @alexis-via help guide you with it?

**Comment by yweng8111** [comment]
> @yweng8111 What is your pull request about? 

It's a small new feature on model donation.tax.receipt. I think it should have some states like  "sent" and "printed". So that the user can know if he has send the tax receipt to the Spender. 
After that we can add more features like following use case. 
If the user want to change the donation, he should be warned that the Tax receipt is already printed and sent.

> Did @alexis-via help guide you with it?

Did I do something wrong or forget some other steps? I just don't know how fix that pre-commit error, as I didn't get it locally.

**Comment by melutovich** [comment]
@yweng8111 

I'm a potential user of the donation package so also can't help with solving the pre-checks.  I found them on the closed pull request https://github.com/OCA/donation/actions/runs/4372683274

**Pull request closed without merging**
