### PR TITLE
[14.0] donation: dedicated config page (+ other small improvements)

### PR DESCRIPTION
**Pull request by alexis-via**
Donation app now has a dedicated config page (was previously on the Accounting config page)

Update duplicate settings (copy=False) on few fields of donation.donation
Add thanks_printed in donation tree view with optional="hide"
Add button in donation tree view to mark several donation as thanks_printed=True

### CODE REVIEW

**Comment by rafaelbn** [comment]
Hello @alexis-via , travis is 🔴

**Comment by alexis-via** [comment]
Travis is now green !

**Review by rafaelbn — APPROVED** [review]
Great! Thank you 👍

**Review by albariera — APPROVED** [review]
LGTM :+1:

**Pull request merged**
