### PR TITLE
[10.0] port all donation modules

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Please check conflicts. @alexis-via, you should make only one PR per module. As now, your PRs result unreviewable due to the high quantity of changes. We trust your code a lot, but not asking for the same treatment like other PRs is not fair.

**Comment by alexis-via** [comment]
It is just because the v10 branch was created before the merge of the port to v9. So this branch is currently not derived from the main v10 branch, but from my port-to-v9 branch. That's why there is a conflit and that's why there are a lot of commits.

Don't worry, I'll solve the conflicts when I have time.

I won't do one PR per module, because it's impossible: these modules are a pyramid, so you can't port them independantly one from the other.

I made this PR only to show that there is code for v10 that is currently working fine. So if someone needs support for donation for v10 he can already use it. It still needs to be finalised.

**Comment by pedrobaeza** [comment]
What I do when having several dependent modules is to make the first PR with the base module. At the same time, another PR with all the commits from the first one, and the commits for migrating the dependent module, and indicating that it depends on the other PR (but it's totally usable). As these modules are not very general, let's continue this way, but please take it into account for other times.

**Comment by alexis-via** [comment]
Travis was green on akretion pipe (OCA pipe is too slow ATM).

**Pull request merged**
