### PR TITLE
[12.0] [MIG] donation_sale

### PR DESCRIPTION
**Pull request by nikul-serpentcs**
Donation Sale
=============
To get some real features, you should install the *donation* or the *donation_sale* module.

### CODE REVIEW

**Comment by nikul-serpentcs** [comment]
Depend on #67

**Review by tbaden — APPROVED** [review]
LGTM (code review), waiting for donation_base

**Comment by tbaden** [comment]
@nikul-serpentcs please rebase as donation_base is now available

**Review by alexis-via — APPROVED** [review]
Could be good to up-port this fix: https://github.com/OCA/donation/pull/93

**Pull request closed without merging**
