### PR TITLE
auto-install=True on donation_recurring_tax_receipt

### PR DESCRIPTION
**Pull request by alexis-via**

### CODE REVIEW

**Comment by pedrobaeza** [comment]
Can you check red status?

**Comment by alexis-via** [comment]
This red status is still a mystery for me. I added logs, but I still don't understand why my YAML test sometimes fails with this bad date...

**Comment by yvaucher** [comment]
@alexis-via I would bet on a timezone issue.

Your test ran at 2015-06-14 22:02:44,906

It says that tax_receipt_id.date=2015-06-15

So when setting the timestamp it might have interpreted it as 2015-06-15 00:02

Maybe you could test getting the date with `fields.Date.today()` ?

**Comment by alexis-via** [comment]
@yvaucher I can't use "fields." in YAML test, even with new API

**Comment by yvaucher** [comment]
@alexis-via you need to do `from openerp import fields` first.

See an old API exemple which is working in `addons/project_timesheet/test/work_timesheet.yml`

**Comment by alexis-via** [comment]
I plan to merge it very soon now, so as to update the travis config file with the appropriate version numbers.

**Comment by MOSAMAD** [comment]
:+1:

**Comment by brother-bernard** [comment]
:+1:

**Pull request merged**
